[package]
name = "gammalg"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[features]
default = ["cache"]
cache = ["once_cell"]

[dependencies]
num = { version = "0.4" }
once_cell = { version = "1.10", optional = true }

[dev-dependencies]
pprof = { version = "0.9", features = ["flamegraph"] }
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "flamegraph"
harness = false

[[bench]]
name = "speed"
harness = false
