[package]
name = "gammalg"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[features]
default = []

[dependencies]
num = { version = "0.4" }
smallvec = { version = "1.8" }

[dev-dependencies]
pprof = { version = "0.9", features = ["flamegraph", "criterion"] }
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "flamegraph"
harness = false

[[bench]]
name = "speed"
harness = false
